#Embedded file name: /Users/versonator/Jenkins/live/output/mac_64_static/Release/python-bundle/MIDI Remote Scripts/Ozonic/consts.py
""" The following consts should be substituted with the Sys Ex messages for requesting
a controller's ID response and that response to allow for automatic lookup"""
ID_REQUEST = 0
ID_RESP = 0
GENERIC_STOP = -1
GENERIC_PLAY = -1
GENERIC_REC = -1
GENERIC_LOOP = -1
GENERIC_RWD = -1
GENERIC_FFWD = -1
GENERIC_TRANSPORT = (GENERIC_STOP,
 GENERIC_PLAY,
 GENERIC_REC,
 GENERIC_LOOP,
 GENERIC_RWD,
 GENERIC_FFWD)
GENERIC_ENC1 = 10
GENERIC_ENC2 = 2
GENERIC_ENC3 = 92
GENERIC_ENC4 = 95
GENERIC_ENC5 = 16
GENERIC_ENC6 = 17
GENERIC_ENC7 = 18
GENERIC_ENC8 = 19
GENERIC_ENCODERS = (GENERIC_ENC1,
 GENERIC_ENC2,
 GENERIC_ENC3,
 GENERIC_ENC4,
 GENERIC_ENC5,
 GENERIC_ENC6,
 GENERIC_ENC7,
 GENERIC_ENC8)
GENERIC_SLI1 = 73
GENERIC_SLI2 = 9
GENERIC_SLI3 = 12
GENERIC_SLI4 = 72
GENERIC_SLI5 = 91
GENERIC_SLI6 = 93
GENERIC_SLI7 = 5
GENERIC_SLI8 = 84
GENERIC_SLI9 = 7
GENERIC_SLIDERS = (GENERIC_SLI1,
 GENERIC_SLI2,
 GENERIC_SLI3,
 GENERIC_SLI4,
 GENERIC_SLI5,
 GENERIC_SLI6,
 GENERIC_SLI7,
 GENERIC_SLI8,
 GENERIC_SLI9)
GENERIC_BUT1 = -1
GENERIC_BUT2 = -1
GENERIC_BUT3 = -1
GENERIC_BUT4 = -1
GENERIC_BUT5 = -1
GENERIC_BUT6 = -1
GENERIC_BUT7 = -1
GENERIC_BUT8 = -1
GENERIC_BUT9 = -1
GENERIC_BUTTONS = (GENERIC_BUT1,
 GENERIC_BUT2,
 GENERIC_BUT3,
 GENERIC_BUT4,
 GENERIC_BUT5,
 GENERIC_BUT6,
 GENERIC_BUT7,
 GENERIC_BUT8)
GENERIC_PAD1 = -1
GENERIC_PAD2 = -1
GENERIC_PAD3 = -1
GENERIC_PAD4 = -1
GENERIC_PAD5 = -1
GENERIC_PAD6 = -1
GENERIC_PAD7 = -1
GENERIC_PAD8 = -1
GENERIC_PADS = (GENERIC_PAD1,
 GENERIC_PAD2,
 GENERIC_PAD3,
 GENERIC_PAD4,
 GENERIC_PAD5,
 GENERIC_PAD6,
 GENERIC_PAD7,
 GENERIC_PAD8)