#Embedded file name: /Users/versonator/Jenkins/live/output/mac_64_static/Release/python-bundle/MIDI Remote Scripts/BCF2000/consts.py
""" The following consts should be substituted with the Sys Ex messages for requesting
a controller's ID response and that response to allow for automatic lookup"""
ID_REQUEST = 0
ID_RESP = 0
GENERIC_STOP = 89
GENERIC_PLAY = 90
GENERIC_REC = 91
GENERIC_LOOP = 92
GENERIC_RWD = -1
GENERIC_FFWD = -1
GENERIC_TRANSPORT = (GENERIC_STOP,
 GENERIC_PLAY,
 GENERIC_REC,
 GENERIC_LOOP,
 GENERIC_RWD,
 GENERIC_FFWD)
GENERIC_ENC1 = 1
GENERIC_ENC2 = 2
GENERIC_ENC3 = 3
GENERIC_ENC4 = 4
GENERIC_ENC5 = 5
GENERIC_ENC6 = 6
GENERIC_ENC7 = 7
GENERIC_ENC8 = 8
GENERIC_ENCODERS = (GENERIC_ENC1,
 GENERIC_ENC2,
 GENERIC_ENC3,
 GENERIC_ENC4,
 GENERIC_ENC5,
 GENERIC_ENC6,
 GENERIC_ENC7,
 GENERIC_ENC8)
GENERIC_SLI1 = 81
GENERIC_SLI2 = 82
GENERIC_SLI3 = 83
GENERIC_SLI4 = 84
GENERIC_SLI5 = 85
GENERIC_SLI6 = 86
GENERIC_SLI7 = 87
GENERIC_SLI8 = 88
GENERIC_SLIDERS = (GENERIC_SLI1,
 GENERIC_SLI2,
 GENERIC_SLI3,
 GENERIC_SLI4,
 GENERIC_SLI5,
 GENERIC_SLI6,
 GENERIC_SLI7,
 GENERIC_SLI8)
GENERIC_BUT1 = 73
GENERIC_BUT2 = 74
GENERIC_BUT3 = 75
GENERIC_BUT4 = 76
GENERIC_BUT5 = 77
GENERIC_BUT6 = 78
GENERIC_BUT7 = 79
GENERIC_BUT8 = 80
GENERIC_BUT9 = -1
GENERIC_BUTTONS = (GENERIC_BUT1,
 GENERIC_BUT2,
 GENERIC_BUT3,
 GENERIC_BUT4,
 GENERIC_BUT5,
 GENERIC_BUT6,
 GENERIC_BUT7,
 GENERIC_BUT8)
GENERIC_PAD1 = -1
GENERIC_PAD2 = -1
GENERIC_PAD3 = -1
GENERIC_PAD4 = -1
GENERIC_PAD5 = -1
GENERIC_PAD6 = -1
GENERIC_PAD7 = -1
GENERIC_PAD8 = -1
GENERIC_PADS = (GENERIC_PAD1,
 GENERIC_PAD2,
 GENERIC_PAD3,
 GENERIC_PAD4,
 GENERIC_PAD5,
 GENERIC_PAD6,
 GENERIC_PAD7,
 GENERIC_PAD8)