#Embedded file name: /Users/versonator/Jenkins/live/output/mac_64_static/Release/python-bundle/MIDI Remote Scripts/MPK25/consts.py
""" The following consts should be substituted with the Sys Ex messages for requesting
a controller's ID response and that response to allow for automatic lookup"""
ID_REQUEST = 0
ID_RESP = 0
GENERIC_STOP = 117
GENERIC_PLAY = 118
GENERIC_REC = 119
GENERIC_LOOP = -1
GENERIC_RWD = 115
GENERIC_FFWD = 116
GENERIC_TRANSPORT = (GENERIC_STOP,
 GENERIC_PLAY,
 GENERIC_REC,
 GENERIC_LOOP,
 GENERIC_RWD,
 GENERIC_FFWD)
GENERIC_ENC1 = 22
GENERIC_ENC2 = 23
GENERIC_ENC3 = 24
GENERIC_ENC4 = 25
GENERIC_ENC5 = 12
GENERIC_ENC6 = 13
GENERIC_ENC7 = 14
GENERIC_ENC8 = 15
GENERIC_ENCODERS = (GENERIC_ENC1,
 GENERIC_ENC2,
 GENERIC_ENC3,
 GENERIC_ENC4,
 GENERIC_ENC5,
 GENERIC_ENC6,
 GENERIC_ENC7,
 GENERIC_ENC8)
GENERIC_SLI1 = 26
GENERIC_SLI2 = 27
GENERIC_SLI3 = 28
GENERIC_SLI4 = 29
GENERIC_SLI5 = 34
GENERIC_SLI6 = 35
GENERIC_SLI7 = 36
GENERIC_SLI8 = 37
GENERIC_SLIDERS = (GENERIC_SLI1,
 GENERIC_SLI2,
 GENERIC_SLI3,
 GENERIC_SLI4,
 GENERIC_SLI5,
 GENERIC_SLI6,
 GENERIC_SLI7,
 GENERIC_SLI8)
GENERIC_BUT1 = 38
GENERIC_BUT2 = 39
GENERIC_BUT3 = 40
GENERIC_BUT4 = 41
GENERIC_BUT5 = 42
GENERIC_BUT6 = 43
GENERIC_BUT7 = 44
GENERIC_BUT8 = 45
GENERIC_BUT9 = -1
GENERIC_BUTTONS = (GENERIC_BUT1,
 GENERIC_BUT2,
 GENERIC_BUT3,
 GENERIC_BUT4,
 GENERIC_BUT5,
 GENERIC_BUT6,
 GENERIC_BUT7,
 GENERIC_BUT8)
GENERIC_PAD1 = -1
GENERIC_PAD2 = -1
GENERIC_PAD3 = -1
GENERIC_PAD4 = -1
GENERIC_PAD5 = -1
GENERIC_PAD6 = -1
GENERIC_PAD7 = -1
GENERIC_PAD8 = -1
GENERIC_PADS = (GENERIC_PAD1,
 GENERIC_PAD2,
 GENERIC_PAD3,
 GENERIC_PAD4,
 GENERIC_PAD5,
 GENERIC_PAD6,
 GENERIC_PAD7,
 GENERIC_PAD8)