#Embedded file name: /Users/versonator/Jenkins/live/output/mac_64_static/Release/python-bundle/MIDI Remote Scripts/LPD8/consts.py
""" The following consts should be substituted with the Sys Ex messages for requesting
a controller's ID response and that response to allow for automatic lookup"""
ID_REQUEST = 0
ID_RESP = 0
GENERIC_STOP = 23
GENERIC_PLAY = 24
GENERIC_REC = 25
GENERIC_LOOP = 20
GENERIC_RWD = 21
GENERIC_FFWD = 22
GENERIC_TRANSPORT = (GENERIC_STOP,
 GENERIC_PLAY,
 GENERIC_REC,
 GENERIC_LOOP,
 GENERIC_RWD,
 GENERIC_FFWD)
GENERIC_ENC1 = 1
GENERIC_ENC2 = 2
GENERIC_ENC3 = 3
GENERIC_ENC4 = 4
GENERIC_ENC5 = 5
GENERIC_ENC6 = 6
GENERIC_ENC7 = 7
GENERIC_ENC8 = 8
GENERIC_ENCODERS = (GENERIC_ENC1,
 GENERIC_ENC2,
 GENERIC_ENC3,
 GENERIC_ENC4,
 GENERIC_ENC5,
 GENERIC_ENC6,
 GENERIC_ENC7,
 GENERIC_ENC8)
GENERIC_SLI1 = 110
GENERIC_SLI2 = 111
GENERIC_SLI3 = 112
GENERIC_SLI4 = 113
GENERIC_SLI5 = 114
GENERIC_SLI6 = 115
GENERIC_SLI7 = 116
GENERIC_SLI8 = 117
GENERIC_SLIDERS = (GENERIC_SLI1,
 GENERIC_SLI2,
 GENERIC_SLI3,
 GENERIC_SLI4,
 GENERIC_SLI5,
 GENERIC_SLI6,
 GENERIC_SLI7,
 GENERIC_SLI8)
GENERIC_BUT1 = 52
GENERIC_BUT2 = 53
GENERIC_BUT3 = 54
GENERIC_BUT4 = 55
GENERIC_BUT5 = 56
GENERIC_BUT6 = 57
GENERIC_BUT7 = 58
GENERIC_BUT8 = 59
GENERIC_BUT9 = 60
GENERIC_BUTTONS = (GENERIC_BUT1,
 GENERIC_BUT2,
 GENERIC_BUT3,
 GENERIC_BUT4,
 GENERIC_BUT5,
 GENERIC_BUT6,
 GENERIC_BUT7,
 GENERIC_BUT8)
GENERIC_PAD1 = 80
GENERIC_PAD2 = 81
GENERIC_PAD3 = 82
GENERIC_PAD4 = 83
GENERIC_PAD5 = 85
GENERIC_PAD6 = 86
GENERIC_PAD7 = 87
GENERIC_PAD8 = 88
GENERIC_PADS = (GENERIC_PAD1,
 GENERIC_PAD2,
 GENERIC_PAD3,
 GENERIC_PAD4,
 GENERIC_PAD5,
 GENERIC_PAD6,
 GENERIC_PAD7,
 GENERIC_PAD8)